<a target="_blank" href="https://colab.research.google.com/github/Xornotor/PPGEE-Otimizacao-Exercicios/blob/main/Lista-01-A/Q5.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# **Lista de Exercícios 01-A | Questão 5**

**UFBA** | PPGEE0016 - Otimização

**Aluno:** André Paiva Conrado Rodrigues

In [1]:
# Importação de dependências e configurações de pretty-printing
import numpy as np
from scipy.optimize import linprog
np.set_printoptions(precision=3, suppress=True, linewidth=150)

## **1. Filtragem do problema**

### **Isolando a Gasolina Bruta 1**

Analisando o critério de Octanagem, Podemos perceber que o Combustível 1 só pode ser feito a partir da Gasolina Bruta 4; que o Combustível 2 pode ser feito a partir das Gasolinas Brutas 3 e 4; e que o Combustível 3 pode ser feito a partir das Gasolinas Brutas 2, 3 e 4.

Nesse sentido, podemos perceber imediatamente que a Gasolina Bruta 1 não será utilizada na cadeia produtiva, e que portanto, todos os 4000L serão vendidos, o que já garante um lucro de:

$$4000 \cdot (1,85 - 1,02) = \textrm{R\$ } 3320$$

O valor de R$ 3320 será isolado para soma posterior.

## **2. Problema de otimização**

Considerando:

*   $x_1$ a quantidade usada de Gasolina Bruta 4 para produzir Combustível 1;
*   $x_2$ a quantidade usada de Gasolina Bruta 3 para produzir Combustível 2;
*   $x_3$ a quantidade usada de Gasolina Bruta 4 para produzir Combustível 2;
*   $x_4$ a quantidade usada de Gasolina Bruta 2 para produzir Combustível 3;
*   $x_5$ a quantidade usada de Gasolina Bruta 3 para produzir Combustível 3;
*   $x_6$ a quantidade usada de Gasolina Bruta 4 para produzir Combustível 3;
*   $x_7$ a quantidade vendida de Gasolina Bruta 2;
*   $x_8$ a quantidade vendida de Gasolina Bruta 3;
*   $x_9$ a quantidade vendida de Gasolina Bruta 4;

Temos os seguintes lucros:

*   $(5,15 - 2,75)x_1 = 2,4x_1$;
*   $(3,95 - 1,35)x_2 = 2,6x_2$;
*   $(3,95 - 2,75)x_3 = 1,2x_3$;
*   $(2,99 - 1,15)x_4 = 1,84x_4$;
*   $(2,99 - 1,35)x_5 = 1,64x_5$;
*   $(2,99 - 2,75)x_6 = 0,24x_6$;
*   $(1,85 - 1,15)x_7 = 0,7x_7$;
*   $(2,95 - 1,35)x_8 = 1,6x_8$;
*   $(2,95 - 2,75)x_9 = 0,2x_9$.

Temos o seguinte problema de otimização:

\begin{equation*}
\begin{aligned}
\text{Maximizar} \\
&& Z = 2.4x_1 + 2.6x_2 + 1.2x_3 + 1.84x_4 + 1.64x_5 + 0.24x_6 + 0.7x_7 + 1.6x_8 + 0.2x_9 \\
\text{Sujeito a} \\
c_{1}: && x_1 \leq 10000 \\
c_{2}: && x_4 + x_5 + x_6 \geq 15000 \\
c_{3}: && x_4 + x_7 = 5050 \\
c_{4}: && x_2 + x_5 + x_8 = 7100 \\
c_{5}: && x_1 + x_3 + x_6 + x_9 = 4300 \\
&& x_1, x_2, x_3, x_4, x_5, x_6, x_7, x_8, x_9 \geq 0 \\
\end{aligned}
\end{equation*}

## **3. Solução manual por Simplex**

Primeiramente, é necessário colocar a função objetivo e as restrições na forma padrão, adicionando variáveis de folga para eliminar as desigualdades. Deste modo, o problema é reformulado da seguinte maneira:

\begin{equation*}
\begin{aligned}
\text{Maximizar} \\
&& Z - 2.4x_1 - 2.6x_2 - 1.2x_3 - 1.84x_4 - 1.64x_5 - 0.24x_6 - 0.7x_7 - 1.6x_8 - 0.2x_9 = 0 \\
\text{Sujeito a} \\
c_{1}: && x_1 + x_{10} = 10000 \\
c_{2}: && -x_4 - x_5 - x_6 + x_{11} = -15000 \\
c_{3}: && x_4 + x_7 = 5050 \\
c_{4}: && x_2 + x_5 + x_8 = 7100 \\
c_{5}: && x_1 + x_3 + x_6 + x_9 = 4300 \\
&& x_1, x_2, x_3, x_4, x_5, x_6, x_7, x_8, x_9, x_{10}, x_{11} \geq 0 \\
\end{aligned}
\end{equation*}

Montando a matriz $\boldsymbol{M}$ para o algoritmo simplex:

| ////  | $Z$ | $x_{1}$ | $x_{2}$ | $x_{3}$ | $x_{4}$ | $x_{5}$ | $x_{6}$ | $x_{7}$ | $x_{8}$ | $x_{9}$ | $x_{10}$ | $x_{11}$ | $b$   |
|-------|-----|---------|---------|---------|---------|---------|---------|---------|---------|---------|----------|----------|-------|
| $L_1$ | 0   | 1       | 0       | 0       | 0       | 0       | 0       | 0       | 0       | 0       | 1        | 0        | 10000 |
| $L_2$ | 0   | 0       | 0       | 0       |  1      |  1      |  1      | 0       | 0       | 0       | 0        | -1       | -15000|
| $L_3$ | 0   | 0       | 0       | 0       | 1       | 0       | 0       | 1       | 0       | 0       | 0        | 0        | 5050  |
| $L_4$ | 0   | 0       | 1       | 0       | 0       | 1       | 0       | 0       | 1       | 0       | 0        | 0        | 7100  |
| $L_5$ | 0   | 1       | 0       | 1       | 0       | 0       | 1       | 0       | 0       | 1       | 0        | 0        | 4300  |
| $L_6$ | 1   | -2,4    | -2,6    | -1,2    | -1,84   | -1,64   | -0,24   | -0,7    | -1,6    | -0,2    | 0        | 0        | 0     |

In [2]:
M = np.array([
    [0,     1,      0,     0,      0,     0,      0,     0,      0,     0,      1,     0,     10000],
    [0,     0,      0,     0,     -1,    -1,     -1,     0,      0,     0,      0,     1,    -15000],
    [0,     0,      0,     0,      1,     0,      0,     1,      0,     0,      0,     0,     5050 ],
    [0,     0,      1,     0,      0,     1,      0,     0,      1,     0,      0,     0,     7100 ],
    [0,     1,      0,     1,      0,     0,      1,     0,      0,     1,      0,     0,     4300 ],
    [1,     -2.4,   -2.6,  -1.2,   -1.84, -1.64,  -0.24, -0.7,   -1.6,  -0.2,   0,     0,     0    ],
], dtype=np.float64)

### **Iteração 1**

Iniciamos selecionando a coluna de $x_2$ como **coluna pivô** por possuir custo com menor valor (-2,6). A partir disto, efetuamos a divisão element-wise dos elementos da coluna $x_2$ pelos elementos da coluna $b$, e selecionando a menor magnitude, obtemos a **linha pivô**.

In [3]:
b_col = 12
pivot_col = 2
div_pivot_b_cols = (M.T[b_col] / M.T[pivot_col])[:-1]
div_pivot_b_cols

<ipython-input-3-75da214d42f6>:3: RuntimeWarning: divide by zero encountered in divide
  div_pivot_b_cols = (M.T[b_col] / M.T[pivot_col])[:-1]


array([  inf,  -inf,   inf, 7100.,   inf])

In [4]:
pivot_row = np.argmin(div_pivot_b_cols)
pivot_row

1

Logo, a linha pivô é $L_4$. Não é necessária substitução, pois o elemento pivô  $M_{43}$ é igual a 1. A ideia agora é zerar todos os outros elementos da coluna $x_2$. Para tanto, fazemos as seguintes substituições:

*   $L_6 \rightarrow L_6 + 2.6L_4$

In [5]:
for i in range(M.shape[0]):
    if(i != pivot_row):
        M[i] -= M[i][pivot_col] * M[pivot_row]
M

array([[     0.  ,      1.  ,      0.  ,      0.  ,      0.  ,      0.  ,      0.  ,      0.  ,      0.  ,      0.  ,      1.  ,      0.  ,
         10000.  ],
       [     0.  ,      0.  ,      0.  ,      0.  ,     -1.  ,     -1.  ,     -1.  ,      0.  ,      0.  ,      0.  ,      0.  ,      1.  ,
        -15000.  ],
       [     0.  ,      0.  ,      0.  ,      0.  ,      1.  ,      0.  ,      0.  ,      1.  ,      0.  ,      0.  ,      0.  ,      0.  ,
          5050.  ],
       [     0.  ,      0.  ,      1.  ,      0.  ,      1.  ,      2.  ,      1.  ,      0.  ,      1.  ,      0.  ,      0.  ,     -1.  ,
         22100.  ],
       [     0.  ,      1.  ,      0.  ,      1.  ,      0.  ,      0.  ,      1.  ,      0.  ,      0.  ,      1.  ,      0.  ,      0.  ,
          4300.  ],
       [     1.  ,     -2.4 ,     -2.6 ,     -1.2 ,     -4.44,     -4.24,     -2.84,     -0.7 ,     -1.6 ,     -0.2 ,      0.  ,      2.6 ,
        -39000.  ]])

### **Iteração 2**

Agora, a coluna pivô é a coluna de $x_1$. Efetuamos a divisão element-wise entre a coluna $x_1$ e a coluna $b$ para obter a linha pivô:

In [6]:
pivot_col = 1
div_pivot_b_cols = (M.T[b_col] / M.T[pivot_col])[:-1]
div_pivot_b_cols

<ipython-input-6-35561d2b2d31>:2: RuntimeWarning: divide by zero encountered in divide
  div_pivot_b_cols = (M.T[b_col] / M.T[pivot_col])[:-1]


array([10000.,   -inf,    inf,    inf,  4300.])

In [7]:
pivot_row = np.argmin(div_pivot_b_cols)
pivot_row

1

A linha pivô agora é $L_5$. Novamente, não são necessárias substituições, pois $M_{52}$ é igual a 1. Para zerar os outros elementos da coluna $x_1$:

*   $L_1 \rightarrow L_1 - L_5$
*   $L_6 \rightarrow L_6 + 2.4L_5$

In [8]:
for i in range(M.shape[0]):
    if(i != pivot_row):
        M[i] -= M[i][pivot_col] * M[pivot_row]
M

array([[     0.  ,      1.  ,      0.  ,      0.  ,      1.  ,      1.  ,      1.  ,      0.  ,      0.  ,      0.  ,      1.  ,     -1.  ,
         25000.  ],
       [     0.  ,      0.  ,      0.  ,      0.  ,     -1.  ,     -1.  ,     -1.  ,      0.  ,      0.  ,      0.  ,      0.  ,      1.  ,
        -15000.  ],
       [     0.  ,      0.  ,      0.  ,      0.  ,      1.  ,      0.  ,      0.  ,      1.  ,      0.  ,      0.  ,      0.  ,      0.  ,
          5050.  ],
       [     0.  ,      0.  ,      1.  ,      0.  ,      1.  ,      2.  ,      1.  ,      0.  ,      1.  ,      0.  ,      0.  ,     -1.  ,
         22100.  ],
       [     0.  ,      1.  ,      0.  ,      1.  ,      1.  ,      1.  ,      2.  ,      0.  ,      0.  ,      1.  ,      0.  ,     -1.  ,
         19300.  ],
       [     1.  ,     -2.4 ,     -2.6 ,     -1.2 ,     -6.84,     -6.64,     -5.24,     -0.7 ,     -1.6 ,     -0.2 ,      0.  ,      5.  ,
        -75000.  ]])

### **Iteração 3**

Agora, a coluna pivô é a coluna de $x_4$. Efetuamos a divisão element-wise entre a coluna $x_4$ e a coluna $b$ para obter a linha pivô:

In [9]:
pivot_col = 4
div_pivot_b_cols = (M.T[b_col] / M.T[pivot_col])[:-1]
div_pivot_b_cols

array([25000., 15000.,  5050., 22100., 19300.])

In [10]:
pivot_row = np.argmin(div_pivot_b_cols)
pivot_row

2

A linha pivô agora é $L_3$. Novamente, não são necessárias substituições, pois $M_{25}$ é igual a 1. Para zerar os outros elementos da coluna $x_4$:

*   $L_2 \rightarrow L_2 - L_3$
*   $L_6 \rightarrow L_6 + 1.84L_3$

In [11]:
for i in range(M.shape[0]):
    if(i != pivot_row):
        M[i] -= M[i][pivot_col] * M[pivot_row]
M

array([[     0.  ,      1.  ,      0.  ,      0.  ,      0.  ,      1.  ,      1.  ,     -1.  ,      0.  ,      0.  ,      1.  ,     -1.  ,
         19950.  ],
       [     0.  ,      0.  ,      0.  ,      0.  ,      0.  ,     -1.  ,     -1.  ,      1.  ,      0.  ,      0.  ,      0.  ,      1.  ,
         -9950.  ],
       [     0.  ,      0.  ,      0.  ,      0.  ,      1.  ,      0.  ,      0.  ,      1.  ,      0.  ,      0.  ,      0.  ,      0.  ,
          5050.  ],
       [     0.  ,      0.  ,      1.  ,      0.  ,      0.  ,      2.  ,      1.  ,     -1.  ,      1.  ,      0.  ,      0.  ,     -1.  ,
         17050.  ],
       [     0.  ,      1.  ,      0.  ,      1.  ,      0.  ,      1.  ,      2.  ,     -1.  ,      0.  ,      1.  ,      0.  ,     -1.  ,
         14250.  ],
       [     1.  ,     -2.4 ,     -2.6 ,     -1.2 ,      0.  ,     -6.64,     -5.24,      6.14,     -1.6 ,     -0.2 ,      0.  ,      5.  ,
        -40458.  ]])

Repare que a linha de coeficientes de custo agora tem apenas valores positivos! Isto significa que chegamos ao final das iterações.

## **4. Solução por algoritmo**

In [12]:
A = np.array([
    [0,      0,     0,     -1,    -1,     -1,     0,      0,     0],
    [0,      0,     0,      1,     0,      0,     1,      0,     0],
    [0,      1,     0,      0,     1,      0,     0,      1,     0],
    [1,      0,     1,      0,     0,      1,     0,      0,     1],
])

b = [-15000, 5050, 7100, 4300]

coef = np.array([2.4, 2.6, 1.2, 1.84, 1.64, 0.24, 0.7, 1.6, 0.2]) * (-1)

var_bounds = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0], [10000, np.inf, np.inf, np.inf, np.inf, np.inf, np.inf, np.inf, np.inf]]).T

res = linprog(coef, A_ub=A, b_ub=b, bounds=var_bounds, method='highs')
res

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -25100.0
              x: [ 1.450e+03  0.000e+00  0.000e+00  5.050e+03  7.100e+03
                   2.850e+03  0.000e+00  0.000e+00  0.000e+00]
            nit: 0
          lower:  residual: [ 1.450e+03  0.000e+00  0.000e+00  5.050e+03
                              7.100e+03  2.850e+03  0.000e+00  0.000e+00
                              0.000e+00]
                 marginals: [ 0.000e+00  1.200e+00  1.200e+00  0.000e+00
                              0.000e+00  0.000e+00  3.300e+00  2.200e+00
                              2.200e+00]
          upper:  residual: [ 8.550e+03        inf        inf        inf
                                    inf        inf        inf        inf
                                    inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00  0.000e+00  